package Day_05.threads;

public class ResultTask extends Thread {
    public void run() {
        System.out.println("Result generated by: "+ Thread.currentThread().getName());
    }
    public static void main(String[] args) {
        ResultTask t1 = new ResultTask();
        t1.run(); // normal execution -> Always the main Thread
        t1.start(); // multithreading -> T-0, T-1, T-2, T-3....     
        // start() internally calls run()
        // thread cannot be started twice
    }
}
